In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
list=[10,20,30,40]

print(list)

[10, 20, 30, 40]


In [ ]:
import numpy as np
list_1=[10,20,30,40]
print(list_1)

[10, 20, 30, 40]


In [ ]:
import numpy as np
list_1=[10,20,30,40]
print(type(list_1))
arr=np.array(list_1)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
list_1=[10,20,30,40]
arr=np.array(list_1)
b=arr+5
print(b)
print(arr)

[15 25 35 45]
[10 20 30 40]


In [ ]:
import numpy as np
list_1=[10,20,30,40]
arr=np.array(list_1)
b=arr+5
print("main array values are:",arr)
print("updated values are:",b)

main array values are: [10 20 30 40]
updated values are: [15 25 35 45]


In [ ]:
import sys
list=[10,20,30,40]
bytes=sys.getsizeof(list)
print(bytes)

88


In [ ]:
import sys
import numpy as np
list_2=[10,20,30,40]
arr=np.array(list_2)
bytes=sys.getsizeof(arr)
print(bytes)

144


In [ ]:
import sys
import numpy as np
list_2=[10,20,30,40,50,60,70,80,90,10,23,29,35,98,86,65,45,34]
arr=np.array(list_2)
bytes=sys.getsizeof(arr)
print(bytes)


256


In [ ]:
import sys
list_2=[10,20,30,40,50,60,70,80,90,10,23,29,35,98,86,65,45,34]
bytes=sys.getsizeof(list_2)
print(bytes)


200


In [ ]:
import time
import numpy as np
list_4=[10,20,30,40,50,60,49,38,68,46,38,586]
start=time.time()
arr=np.array(list_4)
arr=arr+1
end=time.time()
print("python time:",end-start,"seconds")
print(arr)

python time: 0.00011897087097167969 seconds
[ 11  21  31  41  51  61  50  39  69  47  39 587]


In [ ]:
import time
import numpy as np
list_4=[10,20,30,40,50,60,70,80,90,34,56,78]
start=time.time()
arr=np.array(list_4)
arr=arr+1
end=time.time()
print(end-start)
print(arr)



0.0001537799835205078
[11 21 31 41 51 61 71 81 91 35 57 79]


In [ ]:
numbers=[10,20,30,40,50,60,70,80,90]
for i in numbers:
    print(i,id(i),id(numbers))

10 11645640 137844463774080
20 11645960 137844463774080
30 11646280 137844463774080
40 11646600 137844463774080
50 11646920 137844463774080
60 11647240 137844463774080
70 11647560 137844463774080
80 11647880 137844463774080
90 11648200 137844463774080


In [ ]:
import numpy as np
numbers=[10,20,30,40,50,60,70,80,90]
arr=np.array(numbers)
for i in arr:
    print(i,id(i),id(numbers))

10 137844468768784 137844463615616
20 137844468766992 137844463615616
30 137844468772848 137844463615616
40 137844468768784 137844463615616
50 137844468766992 137844463615616
60 137844468772848 137844463615616
70 137844468768784 137844463615616
80 137844468766992 137844463615616
90 137844468772848 137844463615616
