In [ ]:
for num in range(2,101):
  for i in range(2,num):
    if (num%i==0):
      break
  else:
      print(num,end=" ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [ ]:
rows = 5
for i in range(1, rows + 1):
    asterisks_string = " ".join(["*"] * i)
    total_width = 2 * rows - 1
    leading_spaces = total_width - len(asterisks_string)
    print(" " * leading_spaces + asterisks_string)

        *
      * *
    * * *
  * * * *
* * * * *


In [ ]:
list_1=[10,20,30]
print(list_1)
print(id(list_1))

[10, 20, 30]
132685807684416


In [ ]:
list_1[0]=40
print(list_1)
print(id(list_1))

[40, 20, 30]
132685807684416


In [ ]:
name="kle college"
print(name)
print(id(name))

kle college
132685807505776


In [ ]:
a=20
print(type(a))

<class 'int'>


In [ ]:
import numpy as np
arr=np.array([10,20,30,40.0,"kle"])
print(arr)
print(arr.dtype)

['10' '20' '30' '40.0' 'kle']
<U32


In [ ]:
import numpy as np
arr=np.array([10,20,30,40.0,3+2j])
print(arr)
print(arr.dtype)

[10.+0.j 20.+0.j 30.+0.j 40.+0.j  3.+2.j]
complex128


In [ ]:
import numpy as np
arr=np.array([10,20,30,40.0,3+2j,"kle"])
print(arr)
print(arr.dtype)

['10' '20' '30' '40.0' '(3+2j)' 'kle']
<U64


In [ ]:
import numpy as np
arr=np.array([10,20,30,40.0,"kle"],dtype=object)
print(arr)
print(arr.dtype)

[10 20 30 40.0 'kle']
object


In [ ]:
import numpy as np
arr=np.array([10,20,30,40.0,900,],dtype=float)
print(arr)
print(arr.dtype)

[ 10.  20.  30.  40. 900.]
float64


In [ ]:
import numpy as np
arr=np.array([10,20,30,40.0,900,],dtype=str)
print(arr)
print(arr.dtype)

['10' '20' '30' '40.0' '900']
<U4


In [ ]:
import numpy as np
arr=np.array([10,20,30,40.0,900,],dtype=float)
print(arr)
print(arr.dtype)

[ 10.  20.  30.  40. 900.]
float64


In [ ]:
 number=10
 arr_1=np.array(number)
 print(arr_1)
 print("dimension:",arr_1.ndim)
 print("shape:",arr_1.shape)
 print("datatype:",arr_1.dtype)
 print("size:",arr_1.size)

10
dimension: 0
shape: ()
datatype: int64
size: 1


In [ ]:
 number="kle college"
 arr_1=np.array(number)
 print(arr_1)
 print("dimension:",arr_1.ndim)
 print("shape:",arr_1.shape)
 print("datatype:",arr_1.dtype)
 print("size:",arr_1.size)

kle college
dimension: 0
shape: ()
datatype: <U11
size: 1


In [ ]:
 number=10.22
 arr_1=np.array(number)
 print(arr_1)
 print("dimension:",arr_1.ndim)
 print("shape:",arr_1.shape)
 print("datatype:",arr_1.dtype)
 print("size:",arr_1.size)

10.22
dimension: 0
shape: ()
datatype: float64
size: 1


In [ ]:
number=[10,20,30 ,"45.5"]
arr_1=np.array(number)
print(arr_1)
print("dimension:",arr_1.ndim)
print("shape:",arr_1.shape)
print("datatype:",arr_1.dtype)
print("size:",arr_1.size)

['10' '20' '30' '45.5']
dimension: 1
shape: (4,)
datatype: <U21
size: 4


In [ ]:
number=[10,20,30 ,"kle"]
arr_1=np.array(number)
print(arr_1)
print("dimension:",arr_1.ndim)
print("shape:",arr_1.shape)
print("datatype:",arr_1.dtype)
print("size:",arr_1.size)

['10' '20' '30' 'kle']
dimension: 1
shape: (4,)
datatype: <U21
size: 4


In [ ]:
import numpy as np
arr=np.array(range(1,100,4*4),dtype=int)
print(arr)

[ 1 17 33 49 65 81 97]


In [ ]:
import numpy as np
arr=np.array(range(1,100,10),dtype=bool)
print(arr)

[ True  True  True  True  True  True  True  True  True  True]


In [ ]:
import numpy as np
arr=np.array(range(1,100),dtype=int)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
import numpy as np
arr=np.array(range(1,5),dtype=int)
print(arr)

[1 2 3 4]


In [ ]:
import numpy as np
arr=np.array(range(1,5),dtype=int)
arr.shape=(2,2)
print(arr)

print("dimension:",arr_1.ndim)
print("shape:",arr_1.shape)
print("datatype:",arr_1.dtype)
print("size:",arr_1.size)

[[1 2]
 [3 4]]
dimension: 1
shape: (4,)
datatype: <U21
size: 4


In [ ]:
import numpy as np
arr=np.array(range(1,16),dtype=int)
arr=arr.reshape(5,3)
print(arr)

print("dimension:",arr_1.ndim)
print("shape:",arr_1.shape)
print("datatype:",arr_1.dtype)
print("size:",arr_1.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
dimension: 1
shape: (4,)
datatype: <U21
size: 4


In [ ]:
import numpy as np
list=["kle",1,2,3,4,14.6,3+2j,"boss","abc",2*9]
arr=np.array(list)
arr=arr.reshape(2,5)
print(arr)

print("dimension:",arr_1.ndim)
print("shape:",arr_1.shape)
print("datatype:",arr_1.dtype)
print("size:",arr_1.size)

[['kle' '1' '2' '3' '4']
 ['14.6' '(3+2j)' 'boss' 'abc' '18']]
dimension: 1
shape: (4,)
datatype: <U21
size: 4


In [ ]:
import numpy as np
list=["kle",1,2,3,4,14.6,3+2j,"boss","abc",2*9]
arr=np.array(list)
arr=arr.reshape(2,5)
print(arr)

print("dimension:",arr_1.ndim)
print("shape:",arr_1.shape)
print("datatype:",arr_1.dtype)
print("size:",arr_1.size)
print()
print()
print()

print("============2d to 1d=============")
arr.shape=(10,)

print(arr)

arr=np.array(range(1,25))
arr.shape=[2,4,3]
print(arr)

[['kle' '1' '2' '3' '4']
 ['14.6' '(3+2j)' 'boss' 'abc' '18']]
dimension: 1
shape: (4,)
datatype: <U21
size: 4



============2d to 1d=============
['kle' '1' '2' '3' '4' '14.6' '(3+2j)' 'boss' 'abc' '18']
dimension: 1
shape: (4,)
datatype: <U21
size: 4


In [ ]:
arr=np.array(range(1,25))
arr.shape=[2,4,3]
print(arr)

print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
dimension: 3
shape: (2, 4, 3)
datatype: int64
size: 24


In [ ]:
arr=np.array(range(1,25))
arr.shape=[6,2,2]
print(arr)

print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]

 [[21 22]
  [23 24]]]
dimension: 3
shape: (6, 2, 2)
datatype: int64
size: 24


In [ ]:
arr=np.array(range(1,25))
arr.shape=[6,2,2]
print(arr)
print("=============3d to 2d===========")
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)

print()
print()
print()

arr.shape=[6,4]
print(arr)
print("=============3d to 2d===========")
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)

print()
print()
print()

arr.shape=[24,]
print(arr)
print("=============3d to 2d===========")
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)




[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]

 [[21 22]
  [23 24]]]
=============3d to 2d===========
dimension: 3
shape: (6, 2, 2)
datatype: int64
size: 24



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
=============3d to 2d===========
dimension: 2
shape: (6, 4)
datatype: int64
size: 24



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
=============3d to 2d===========
dimension: 1
shape: (24,)
datatype: int64
size: 24


In [ ]:
l=range(1,49)
arr=np.array(l)
arr=arr.reshape(2,2,4,3)
print(arr)
print("=========================")
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)


[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]
   [19 20 21]
   [22 23 24]]]


 [[[25 26 27]
   [28 29 30]
   [31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]
   [43 44 45]
   [46 47 48]]]]
dimension: 4
shape: (2, 2, 4, 3)
datatype: int64
size: 48


In [ ]:
a=np.arange(1,50)*5
print(a)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225 230 235 240 245]


In [ ]:
arr=np.array(np.arange(1,90,5))
print(arr)

print("=========================")
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)

print()
print()
print()


print("size of arr:",arr.size)
print()
print()
print()


arr.shape=(2,3,3)
print(arr)
print("=========================")
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)


[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86]
dimension: 1
shape: (18,)
datatype: int64
size: 18



size of arr: 18



[[[ 1  6 11]
  [16 21 26]
  [31 36 41]]

 [[46 51 56]
  [61 66 71]
  [76 81 86]]]
dimension: 3
shape: (2, 3, 3)
datatype: int64
size: 18


In [ ]:
import numpy as np
arr=np.linspace(1,100,10,endpoint=False)
print(arr)

[ 1.  10.9 20.8 30.7 40.6 50.5 60.4 70.3 80.2 90.1]


In [ ]:
import numpy as np
arr=np.linspace(1,100,3,endpoint=False,retstep=True,dtype=int)
print(arr)

(array([ 1, 34, 67]), np.float64(33.0))


In [ ]:
import numpy as np
arr=np.linspace(1,100,3,endpoint=False,retstep=True,dtype=int)
print(arr)


(array([ 1, 34, 67]), np.float64(33.0))
<class 'tuple'>


In [ ]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.zeros((5,5),dtype=int)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
import numpy as np
arr=np.linspace(1,100,3,endpoint=False,retstep=True,dtype=int)
print(arr)


(array([ 1, 34, 67]), np.float64(33.0))


In [ ]:
arr=np.ones((3,2,5,5))
print(arr)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


In [ ]:
arr=np.ones((3,5,5),dtype=int)
print(arr)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
arr=np.full((2,2),fill_value="kle")
print(arr)

[['kle' 'kle']
 ['kle' 'kle']]


In [ ]:
larr=np.full((2,2),fill_value="bangloree")
print(arr)

[['bangloree' 'bangloree']
 ['bangloree' 'bangloree']]


In [ ]:
arr=np.identity(5,dtype=int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
arr=np.eye(5,dtype=int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
arr=np.eye(5,k=2,dtype=int)
print(arr)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
arr=np.eye(5,k=-2,dtype=int)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [ ]:
import numpy as np
random_number=np.random.rand()
print(random_number)

0.5631346982714633


In [ ]:
import numpy as np
random_number=np.random.randint(1,10,20)
print(random_number)

[3 9 3 9 7 2 5 7 5 9 2 9 2 3 3 6 8 3 8 6]


In [ ]:
arr=np.random.uniform(1,100,5)
print(arr)

[54.66659199  2.00642386 13.17502504 16.73350699 78.92306686]


In [ ]:
list=[10,20,30,40]
np.random.shuffle(list)
print(list)

[10, 30, 20, 40]


In [ ]:
a=np.arange(0,27).reshape(3,3,3)
print("-------------------")
print("original matrix")
print(a)

print("-------------------")
print("shuffle matrix")
np.random.shuffle(a)
print(a)

-------------------
original matrix
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------------------
shuffle matrix
[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [ ]:
a=[[10,20,30,40],[50,60,70,80]]
b=[[10,20,30,40],[50,60,70,80]]

c=np.hstack((a,b))
print(c)

[[10 20 30 40 10 20 30 40]
 [50 60 70 80 50 60 70 80]]


In [ ]:
a=[[10,20,30,40],[50,60,70,80]]
b=[[10,20,30,40],[50,60,70,80]]

c=np.vstack((a,b))
print(c)

[[10 20 30 40]
 [50 60 70 80]
 [10 20 30 40]
 [50 60 70 80]]


In [ ]:
import numpy as np
arr=np.array(np.arange(1,22)).reshape(3,7)
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [ ]:
print(arr[2,-2])

20


In [ ]:
import numpy as np
arr=np.array(np.arange(1,25)).reshape(3,2,4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [ ]:
print(arr[2,0,-1])

20
